apiVersion: v1
kind: ConfigMap
metadata:
  name: clembot-bot-config
data:
  # run in dev mode (empty string = truthy)
  PROD: ""
  API_URL: "http://clembot-api.clembot-dev.svc.cluster.local:8080/"
  SITE_URL: "https://dev.clembot.io"
  DOCS_URL: "https://docs.clembot.io"
  REPL_URL: "http://clembot-snekbox.clembot-dev.svc.cluster.local:8060/eval"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clembot-api-config
data:
  JwtTokenConfig__Issuer: "https://api-dev.clembot.io"
  JwtTokenConfig__Audience: "https://api-dev.clembot.io"
