apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clembot-dev

resources:
  - ../base
  - namespace.yaml
  # We only run snekbox in the homelab in dev, we will run it over wireguard in prod
  - snekbox

patches:
  - path: configmap-patch.yaml
  - path: bot-deployment-patch.yaml
  - path: api-deployment-patch.yaml
  - path: db-patch.yaml
