apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clembot-site
  annotations:
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    external-dns.alpha.kubernetes.io/hostname: clembot.io
spec:
  rules:
  - host: clembot.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clembot-site
            port:
              number: 3000
