apiVersion: v1
kind: ConfigMap
metadata:
  name: clembot-bot-config
data:
  PROD: "true"
  API_URL: "http://clembot-api.clembot-prod.svc.cluster.local:8080/"
  SITE_URL: "https://clembot.io"
  DOCS_URL: "https://docs.clembot.io"
  REPL_URL: "http://clembot-snekbox.clembot-prod.svc.cluster.local:8060/eval"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clembot-api-config
data:
  JwtTokenConfig__Issuer: "https://api.clembot.io"
  JwtTokenConfig__Audience: "https://api.clembot.io"
