apiVersion: v1
kind: ConfigMap
metadata:
  name: clembot-bot-config
data:
  PROD: "true"
  BOT_PREFIX: "!"
  API_URL: "http://clembot-api.clembot-prod.svc.cluster.local:8080/"
  REPL_URL: "http://clembot-snekbox.clembot-prod.svc.cluster.local:8060/eval"
  ALLOW_BOT_INPUT_IDS: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clembot-api-config
data:
  JwtTokenConfig__Issuer: "https://api.clembot.io"
  JwtTokenConfig__Audience: "https://api.clembot.io"
